### ISSUE TITLE
Implement parser which can add task with end date before start date

### ISSUE THREAD

**Issue by youthinkk** [cs2103aug2015-w11-4j/main#62]
Able to add tasks with end date before start date

**Comment by youthinkk** [comment]
@Foleosy, want to check with you what kind of command will cause this error? Is it possible for you to provide the examples? Thanks!

**Comment by Foleosy** [comment]
Adding camp from 12/11 to 10/11 now gives me date range 12/11 to 17/11; I guess you're pushing the dates one week ahead? (New issue, but related).

I just managed to create the error by doing the following:
1) add task from tuesday to friday -> shows 3 nov - 6 nov
2) edit 1 task by monday -> shows 3 nov to 2 nov
