### ISSUE TITLE
New shortcut keys for undo/redo/home

### ISSUE THREAD

**Issue by Foleosy** [cs2103aug2015-w11-4j/main#84]
Ctrl+Z for undo
Ctrl+Y for redo
Ctrl+H for home
Ctrl+U for show undone
Ctrl+D for show done
Ctrl+S for show all

**Comment by youthinkk** [comment]
Add F1 for help

**Comment by Foleosy** [comment]
Ctrl+Z doesn't work, crashes the program if I try to type after using ctrl+z
Ctrl+Y works fine
Ctrl+H works fine
Ctrl+U works fine
Ctrl+D works fine
F1 works fine
